# Generated by Django 4.0.2 on 2023-05-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
