# Generated by Django 4.0.2 on 2023-05-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_journal_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liveCount', models.IntegerField()),
            ],
        ),
    ]
